version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    depends_on:
      - db
    environment:
      POSTGRES_URI: postgresql://postgres:postgres@db:5432/lightrag
      POSTGRES_TEST_URI: postgresql://postgres:postgres@db:5432/lightrag_test

  db:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lightrag
    ports:
      - "5432:5432"

volumes:
  postgres-data:
